---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
      dataFactoryName: "{{ dataFactoryName }}"
      Storagekey: "{{ Storagekey }}"
      spkey: "{{ spkey }}"
      servicePrincipalId: "{{ servicePrincipalId }}"
      hostSubscriptionId: "{{ hostSubscriptionId }}"
      tenant: "{{ tenant }}"
      ClusterUserName: "{{ ClusterUserName }}"
      ClusterPassword: "{{ ClusterPassword }}"
      sqlseverkey: "{{ sqlseverkey }}"
      environment: "{{ environment }}"
      resourcesgpname: "{{ resourcesgpname }}"
      location: eastus2
      templateLink: 'https://raw.githubusercontent.com/jitusonawane/testing_repo/master/BigData/maindeploy.json'
  tasks:
    - name: Deploy ARM template
      
      azure_rm_deployment:
        subscription_id: "{{ hostSubscriptionId }}"
        client_id: "{{ servicePrincipalId }}"
        tenant: "{{ tenant }}"
        secret: "{{ spkey }}"
        resource_group_name: demojitu
        location: "eastus2"
        state: present
        parameters:
          dataFactoryName: 
            value: "{{ dataFactoryName }}"
          Storagekey: 
            value: "{{ Storagekey }}"
          spkey: 
            value: "{{ spkey }}"
          servicePrincipalId: 
            value: "{{ servicePrincipalId }}"
          hostSubscriptionId: 
            value: "{{ hostSubscriptionId }}"
          tenant: 
            value: "{{ tenant }}"
          ClusterUserName: 
            value: "{{ ClusterUserName }}"
          ClusterPassword: 
            value: "{{ ClusterPassword }}"
          sqlseverkey: 
            value: "{{ sqlseverkey }}"
          resourcesgpname: 
            value: "{{ resourcesgpname }}"
          environment:
            value: "Production"
        template_link: "https://raw.githubusercontent.com/jitusonawane/testing_repo/master/BigData/maindeploy.json"
